export class ErrorCodes {
  static ERROR_MAXIMO_DENUNCIA: string = 'MAXIMO_EMERGENCIAS';
  static ERROR_DENUNCIA_DUPLICADA: string = 'DENUNCIA_REGISTRADA_PREVIAMENTE';
  static ERROR_CONTENIDO_OFENSIVO: string = 'CONTENIDO_OFENSIVO';
  static ERROR_IMAGEN_NO_CORRESPONDE: string = 'IMAGEN_NO_CORRESPONDE';
}
